### ISSUE TITLE
Problem with nested php, slashes are added to php vars

### ISSUE THREAD

**Issue by fakeartist** [emmetio/netbeans#11]
Hi. When I try to add emmet comments in html codes that contain php code, slashes (```\```) are added before php vars.

For example I have this line.

```<td class="item"><?php echo $var; ?></td>```

If I try to comment it, it returns

```<!-- <td class="item"><?php echo \$var; ?></td> -->```

The ```\``` before ```$var``` should not be generated.

The same thing happens if I try to remove tags.

Am I missing something here?

Thanx in advance.

**Comment by junichi11** [comment]
Just workaround: You can use `Ctrl + /`.

**Comment by junichi11** [comment]
Fixed.
