### ISSUE TITLE
Wrap sometimes does nothing.

### ISSUE THREAD

**Issue by BugZappr** [emmetio/netbeans#12]
I've played around with the wrap a bit, and have more info.  If, in the following code:

````
<html>
<head></head>
<body>

This is a test

</body>
</html>
````

you select the line "This is a test", if you select it not including the final newline, it will wrap correctly.  If instead, you select it starting at the beginning of "This", and then move down a line while holding shift, so that the terminal newline of the line is also included, no wrap/expansion take place; even though it does at the example at the Emmet website.

I'm using NB 7.4 patch 1, and Emmet 1.0.1.3; in Win7.  The same thing happens whether or not it is saved as a PHP or an HTML file.

**Comment by junichi11** [comment]
It's reproducible. Thanks for reporting it.

**Comment by junichi11** [comment]
Fixed. Thanks.
