### ISSUE TITLE
Suggestion: When expanding a single tag, don't put it in the "jump between edit points" mode

### ISSUE THREAD

**Issue by BugZappr** [emmetio/netbeans#13]
If I expand a single tag, such as "p", it creates the open and close angle braces, and the close tag.  When I start typing, I see a red box surround what I am typing; but in this context, <Tab> and <Shift-Tab> are not useful.  It is slightly annoying when I reach the end of a line, and hit <Enter>, my cursor jumps to the end of the open tag; i.e. near the start of the line, instead of skipping down to the next line.

Instead, I usually try to get it out of that mode when I expand a tag: sometimes I hit <Escape> to clear the NB close tag code completion, and again to clear the "red box" mode.  Unfortunately, I can't see if it worked, and I sometimes have to hit it again.  I also notice that <Enter> does not navigate to the next edit point on the Emmet example on the Emmet website, but it does in NB.  I think in general, it would be better if either <Enter> did not; or there was a choice to disable <Enter> acting that way.  A minor annoyance, vs. how useful Emmet is, but it would give me more of the feeling of Zen, as it were.  Not terribly pressing, but maybe it wouldn't be very difficult for you.

**Comment by junichi11** [comment]
Dose it means the following? If yes, I can improve it. 

e.g. 

ul>li*3 // expand

```html
<ul>
    <li>something[Enter]<li>
    <li>something[Enter]<li>
    <li>something[Enter]<li>
</ul>|[last caret position here]
```

p // expand
```html
<p>something[Enter]<p>|[last caret position here]
```

Thanks.

**Comment by BugZappr** [comment]
Yes, I believe you have the idea.  That would do nicely; just not:

p // expand

<p>something{caret}[Enter]<p>

which goes back to:

<p>{caret}something<p>

currently.  Skipping the </p> seems better than my suggestion, which was to simply not have 
it in any special mode after the expansion.

**Comment by junichi11** [comment]
Fixed. 

If you want to stop the current position, you can use the `Esc` key.
If you use the `Enter` key, the last caret position move to the end of content.

Thanks.

**Comment by junichi11** [comment]
The new version is available:
https://github.com/emmetio/netbeans/releases/tag/v1.1.1
