### ISSUE TITLE
Netbeans 8.0 (beta)

### ISSUE THREAD

**Issue by Ciantic** [emmetio/netbeans#14]
I couldn't find the plugin in the official list for Netbeans 8.0 beta, I suppose it could be compiled for this?
##

**Comment by junichi11** [comment]
Now, nbms are in https://github.com/emmetio/netbeans/releases. 
Probably, I'll upload it to the Plugin Portal later. But 8.1 not 8.0.

**Comment by atomtigerzoo** [comment]
I created a PR which adds the releases link to the Readme. Maybe you can merge it - if you like it :)

**Comment by junichi11** [comment]
The plugin for NB82 is available in Plugin Portal[1] now. I just close this issue.

[1] http://plugins.netbeans.org/plugin/48315/emmet

Thanks.
