### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by ianchanning** [emmetio/netbeans#15]
On my machine (Windows 8 + Core i7 + 8GB RAM) expanding fairly simple abbreviations takes very long and certainly much longer than the existing Zen Coding plugin. 

With this Emmet plugin and a freshly opened Netbeans 7.3.1 it will take 6.5s to expand `div.test>ul+` with the Zen Coding plugin it will take 3s. 

Subsequent expansions do improve - it takes approx 3s to expand the abbreviation after that. However with the Zen Coding plugin expanding abbreviations are then almost instantaneous.

**Comment by Chris2011** [comment]
Still happens also in the HTML bundled IDE of NetBeans.

**Comment by junichi11** [comment]
I've improved a bit in #25. But it is not perfect, sorry.
