### ISSUE TITLE
Hanging in 8.0.1

### ISSUE THREAD

**Issue by mindofmicah** [emmetio/netbeans#16]
Recently upgraded to 8.0.1 on Ubuntu and the plugin is consistently stalling (more than ever before). It seems to only do it when there is a code completion window open.

**Comment by junichi11** [comment]
Does this still occur in NB81?
Please try useing version 1.1.0 with NB81:
https://github.com/emmetio/netbeans/releases/tag/v1.1.0

**Comment by junichi11** [comment]
If you have some problems, Simply, reopen it or submit a new issue. Thanks.
