### ISSUE TITLE
Expand abbreviation while code completion hang

### ISSUE THREAD

**Issue by hessemanj2100** [emmetio/netbeans#17]
This is a very simple problem to reproduce and I hope this can be fixed without disabling the auto code completion menu. When I attempt to expand an abbreviation while the code completion menu is active, NetBeans completely hangs and I cannot close it. When I press the escape key to close the code completion menu and then expand the abbreviation, it works without a problem. I am running Windows 7 64-bit with NetBeans 8.0.1 and JDK 8u25.

To reproduce the problem, type any simple HTML tag selector, and make sure the code completion menu is shown, then simply expand the abbreviation. Not very nice, eh?

FYI: A simple fix for this bug would be to detect if the code completion menu is open, and if it is, simply close it before running the code to expand the abbreviation.

In the mean time: Open NetBeans and click the Tools menu and then select Options. In the Options dialog box, select Editor and then click the Code Completion tab. Uncheck the check boxes that have the word "Auto" next to them and click the OK button. Code Completion and Emmet do not mix.

NOTE: CTRL + SPACE will give you the code completion menu but you probably already knew that.

Regards,

Josh Hesseman

**Comment by dgsharvesh** [comment]
Frnds me too facing same issue kindly provide some solution

**Comment by junichi11** [comment]
Does this still occur in NB81? https://github.com/emmetio/netbeans/releases/tag/v1.1.0

**Comment by junichi11** [comment]
Duplicate #16
