### ISSUE TITLE
abbreviations not expanding correctly

### ISSUE THREAD

**Issue by diondkb** [emmetio/netbeans#18]
Hi,

When I try expand nav>ul>li using ctrl+alt+n, I get :
nav: ;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
list-style: ;

instead of :-
<nav>
    <ul>
        <li></li>
    </ul>
</nav

I am using netbeans 8.0.2.

Thanks,
Dion

**Comment by vrobik** [comment]
Its because you expand it in css file instead html or php :)

**Comment by junichi11** [comment]
I cannot reproduce it. Probably, @vrobik comment is correct.
