### ISSUE TITLE
Installed in 8.0.2 but not showing keyboard map

### ISSUE THREAD

**Issue by kirangsa** [emmetio/netbeans#19]
Hi Guys,

I have installed it in net-beans 8.0.2. It is is installed successfully. but its not showing the keyboard map.

Can anyone help me on this issue.

Thanks in advance!
Kiran Gopal

**Comment by eaCe** [comment]
Same issue here

**Comment by junichi11** [comment]
Does this still occur in NB8.1?:https://github.com/emmetio/netbeans/releases/tag/v1.1.0

If yes, simply, please reopen this.
