### ISSUE TITLE
There are times where Netbeans freezes up...

### ISSUE THREAD

**Issue by mamarilmanson** [emmetio/netbeans#20]
Many times I expand an abbreviation using the shortcut, Netbeans freezes up...

Windows 7 x86, 2GB workstation...

and btw... any updates on this plugin? please? :)

**Comment by junichi11** [comment]
Where did you download it? Plugin Portal?

If so, please uninstall it once, Then, please try using the following: 
http://download.emmet.io/org-lorenzos-emmet.nbm

**Comment by mamarilmanson** [comment]
@junichi11 ~ Thank you very much... :D

an issue I noticed is that I need to press enter several times in order to get

<div></div> 

to:

<div>

</div> 


:)

**Comment by junichi11** [comment]
> an issue I noticed is that I need to press enter several times in order to get

I'm not sure what does it mean exactly... 
If you have it still, please submit it as a new issue.

Thanks.
