### ISSUE TITLE
I don't see any file with the extension of *.nbm to install Emmet

### ISSUE THREAD

**Issue by Brian1111** [emmetio/netbeans#23]
I have downloaded Emmet for NetBeans 8.1, and unzipped it.  Then tried to install it; however the plugin manager installs only files with the extension *.nbm.  In my downloaded Emmet plugin folder I don't see any file with that extension.  So how should I install Emmet?

**Comment by markiewb** [comment]
A zip file? Where did you download that? Try https://github.com/emmetio/netbeans/issues/3#issuecomment-109258494

**Comment by junichi11** [comment]
Please download the following:
https://github.com/emmetio/netbeans/releases

Thanks.
