### ISSUE TITLE
The .nbm would be nice

### ISSUE THREAD

**Issue by Chaos7703** [emmetio/netbeans#24]
I realize that this is not the ideal situation, but it would be nice if the .nbm were available here.  Thinking that "Emmet" was a Java tool I uninstalled it because only tinker with Java occasionally.  Well, when my expansions stopped working I tried re-installing X from the Netbeans plugin repo, but that subdomain has been down ever since, so I cannot install any plugins and a direct download and manual installation is my only option besides just forgetting them all together and doing it all the slow way.

...just wishful thinking.
Many Thanks,
Todd

**Comment by junichi11** [comment]
I've just added a nbm file to the releases:

https://github.com/emmetio/netbeans/releases
