### ISSUE TITLE
Please bring the new version for 8.2 to the plugin portal and sign it for the plugin center.

### ISSUE THREAD

**Issue by Chris2011** [emmetio/netbeans#31]
As people ask often how to install or where I can find it, plesae make the new version of the plugin available at plugins.netbeans.org and sign it to find it inside the plugin center of NetBeans.

Regards

Chris

**Comment by junichi11** [comment]
Done. http://plugins.netbeans.org/plugin/48315/emmet

Thanks!

**Comment by Chris2011** [comment]
Great, thx.
