### ISSUE TITLE
issue for netbeans ide

### ISSUE THREAD

**Issue by miladbazisaz** [emmetio/netbeans#36]
hi, i search for report issue IDE netbeans, but i not found page for report,
then i found there ! if you know where is send report, please send this title tanks a lot of

in my Linux debian 9.3 stretch with Kernel: x86_64 Linux 4.9.0-5-amd64
i use GNOME Shell Version 3.22.2

some times my IDE netbeans 8.1 close window and lost my codes,

in output syslog is:

Feb  7 11:40:46 mbs netbeans.desktop[4986]: **
Feb  7 11:40:46 mbs netbeans.desktop[4986]: GLib:ERROR:/build/glib2.0-B1uXKV/glib2.0-2.50.3/./glib/ghash.c:373:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)
Feb  7 11:40:46 mbs netbeans.desktop[4986]: /usr/share/netbeans/8.1/platform/lib/nbexec: line 474:  5248 Aborted                 "/usr/lib/jvm/java-8-openjdk-amd64/bin/java" -Djdk.home="/usr/lib/jvm/java-8-openjdk-amd64" -classpath "/usr/share/java/jcodings.jar:/usr/share/netbeans/8.1/platform/lib/boot.jar:/usr/share/netbeans/8.1/platform/lib/org-openide-modules.jar:/usr/share/netbeans/8.1/platform/lib/org-openide-util.jar:/usr/share/netbeans/8.1/platform/lib/org-openide-util-lookup.jar:/usr/share/netbeans/8.1/platform/lib/org-openide-util-ui.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/dt.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar" -Dnetbeans.default_userdir_root="/home/milad/.netbeans" -Dnetbeans.running.environment=gnome -Dnetbeans.dirs="/usr/share/netbeans/8.1/nb:/usr/share/netbeans/8.1/ergonomics:/usr/share/netbeans/8.1/ide:/usr/share/netbeans/8.1/extide:/usr/share/netbeans/8.1/java:/usr/share/netbeans/8.1/apisupport:/usr/share/netbeans/8.1/webcommon:/usr/share/netbeans/8.1/websvccommon:/usr/share/netbeans/8.1/enterprise:/usr/share/netbeans/8.1/mobility:/usr/share/netbeans/8.1/profiler:/usr/share/netbeans/8.1/python:/usr/share/netbeans/8.1/php:/usr/share/netbeans/8.1/identity:/usr/share/netbeans/8.1/harness:/usr/share/netbeans/8.1/cnd:/usr/share/netbeans/8.1/cndext:/usr/share/netbeans/8.1/dlight:/usr/share/netbeans/8.1/groovy:/usr/share/netbeans/8.1/extra:/usr/share/netbeans/8.1/javacard:/usr/share/netbeans/8.1/javafx:" -Dnetbeans.home="/usr/share/netbeans/8.1/platform" '-Dnetbeans.importclass=org.netbeans.upgrade.AutoUpgrade' '-Xmx1024m' '-client' '-Xss2m' '-Xms32m' '-Dapple.laf.useScreenMenuBar=true' '-Dapple.awt.graphics.UseQuartz=true' '-Dsun.java2d.noddraw=true' '-Dsun.java2d.dpiaware=true' '-Dsun.zip.disableMemoryMapping=true' '-Dsun.java2d.pmoffscreen=false' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home/milad/.netbeans/8.1/var/log/heapdump.hprof" org.netbeans.Main --cachedir "/home/milad/.cache/netbeans/8.1" --userdir "/home/milad/.netbeans/8.1" "--branding" "nb" 0<&0
Feb  7 11:40:46 mbs gnome-shell[1168]: setup_framebuffers: assertion 'width > 0' failed
Feb  7 11:40:46 mbs gnome-shell[1168]: setup_framebuffers: assertion 'width > 0' failed
Feb  7 11:40:46 mbs gnome-shell[1168]: setup_framebuffers: assertion 'width > 0' failed
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:52 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:53 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:53 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:40:53 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:01 mbs CRON[6090]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
Feb  7 11:41:02 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:03 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:03 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:03 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:03 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:03 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:05 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Feb  7 11:41:07 mbs gnome-terminal-[5366]: Allocating size to GtkScrollbar 0x55a3370aa2d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

i hope fixed this issue. thanks a lot of <3

**Comment by Chris2011** [comment]
@miladbazisaz is this problem related to the emmet plugin for NetBeans? If not, go to this page: https://issues.apache.org/jira/projects/NETBEANS/issues. Emmet is a plugin for NetBeans.

**Comment by markiewb** [comment]
And you are also using the old NetBeans version 8.1.

NetBeans 8.2 has been released at least one year ago. Try that version.
Perhaps your issue has been already solved AND you get new features and
other bugfixes

**Comment by miladbazisaz** [comment]
@markiewb
@Chris2011 
guys thanks for helping me <3
when i try to update: tools > check for updates
netbeans show me: Your IDE is up to date! There are no updates available.
![screenshot from 2018-02-07 13-23-47](https://user-images.githubusercontent.com/13424532/35910080-6666632e-0bed-11e8-9eac-6e62de49873d.png)

whatever thanks <3

**Comment by Chris2011** [comment]
@miladbazisaz I think it will not show you the update grom 8.1 to 8.2 but we are atm at 8.2 and NB 9 Beta RC3. Come and join the dev mailing lists of apache NetBeans and our slack chan: https://netbeans.signup.team/

**Comment by markiewb** [comment]
You need to install 8.2 manually. There is no notification or function to
upgrade automatically from a previous versions.
