### ISSUE TITLE
License MIT or GPL?

### ISSUE THREAD

**Issue by emilianbold** [emmetio/netbeans#37]
I see on http://plugins.netbeans.org/plugin/48315/emmet that the license is supposed to be MIT for this plugin.

But the module defines `license.file=GNU GPL.txt`

So, the plugin is not under MIT, it's actually GPL 2, correct?

**Comment by junichi11** [comment]
Maybe, GPLv2 is correct because [ZenCodingNetBeansPlugin](https://github.com/lorenzos/ZenCodingNetBeansPlugin) is GPLv2.

**Comment by emilianbold** [comment]
It seems to be so. Please configure a LICENSE file on this GitHub repo so GitHub detects it properly. You could also update the license on the Plugin Portal..

**Comment by junichi11** [comment]
@emilianbold I'll fix it later.
@sergeche If there is a problem, please let me know.
Thanks.

**Comment by sergeche** [comment]
@junichi11  Don’t see a problem here

**Comment by junichi11** [comment]
Done.
