### ISSUE TITLE
Requires Main types of Script languages

### ISSUE THREAD

**Issue by yanuas123** [emmetio/netbeans#39]
When i install the plugin it requires "Main types of Script languages v 1.3.1"
What is it?
Сan someone help me?

**Comment by junichi11** [comment]
Please write your environment:
- NetBeans version
- Plugin version
- etc.

**Comment by yanuas123** [comment]
NetBeans version - 9.0
Plugin version - 1.3.0

When I want to install Emmet, NetBeans show me error: A plug-in module is require The Main Types of scripting languages version> = 1.3.1, the found module has version 1.2.1.

**Comment by yanuas123** [comment]
Windows 7

**Comment by junichi11** [comment]
See requirements: It is for NetBeans 11.0+

Please use version 1.1.2: https://github.com/emmetio/netbeans/releases/tag/v1.1.2
