### ISSUE TITLE
wrappind doesn't work after 1 month added emmet

### ISSUE THREAD

**Issue by Snowbaha** [emmetio/netbeans#4]
Hello,

I am using Netbeans 7.3 with french version on windows seven. I added the module "emmet", It was working until today...
When I load Netbeans, I have this issue : 

orl.lorenzs Output : 
"
org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (emmet-app.js#4385)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
"
Full error here : http://pastebin.com/ajHcXKUf

I can't use wrapping element, but expand element still working.

There is a problem with EMMET or it's another thing which do a "conflict" ?

Thanks.

**Comment by junichi11** [comment]
Does this still occur in NB81? (If yes, simply, please reopen it.)
Please try useing version 1.1.0 with NB81:
https://github.com/emmetio/netbeans/releases/tag/v1.1.0
