### ISSUE TITLE
[suggestion] Update

### ISSUE THREAD

**Issue by Tox86** [emmetio/netbeans#41]
Hello everyone, please update for Apache Netbeans 12.0

Cheers

**Comment by junichi11** [comment]
Didn't this work? : https://github.com/emmetio/netbeans/releases/tag/v1.3.0
I'll recreate the nbm with NetBeans 12.0.

**Comment by junichi11** [comment]
Done: https://github.com/emmetio/netbeans/releases/tag/v1.4.0
