### ISSUE TITLE
Plugin not available on Available Plugins for Netbeans 12.2

### ISSUE THREAD

**Issue by jshster** [emmetio/netbeans#42]
I was using this plugin in Netbeans 11.3 but it doesn't appear in the list of available plugins for 12.2.   I can't seem to find the .npm file either in the repo so can't install that way either.

Will it be deployed any time soon?  Any other way of installing?

**Comment by junichi11** [comment]
Please download and install it manually: https://github.com/emmetio/netbeans/releases/tag/v1.4.0
