### ISSUE TITLE
Disable completion window display after abbreviation expansion in css

### ISSUE THREAD

**Issue by yadenis** [emmetio/netbeans#44]
Hello,
Is it possible to disable the display of the completion window after expanding the abbreviation in css?

Demo:
![emmet](https://user-images.githubusercontent.com/5316579/177819327-1e6d2bb5-d667-45c3-9899-6ebabfc8f1d0.gif)

Automatic popup settings are disabled and do not affect the result:
![image](https://user-images.githubusercontent.com/5316579/177819527-34c8e2ff-3a40-41c9-ace5-2a5760ee5b5e.png)

NetBeans 14

**Comment by junichi11** [comment]
Could you try to use NB15?

**Comment by Chris2011** [comment]
Seems that the code completion not comes up in NetBeans 15.

**Comment by yadenis** [comment]
It seems that NetBeans 15 does not have this problem. Thanks for answers!
