### ISSUE TITLE
NetBeans TAB support

### ISSUE THREAD

**Issue by insign** [emmetio/netbeans#5]
NB don't support TAB abbreviation with disable the default action of the TAB

**Comment by YannickGagnon** [comment]
Still nothing regarding this request?

**Comment by Chris2011** [comment]
Unfortunately not I think :( hope that someone can fork it and can work on it.

**Comment by insign** [comment]
I still recommending to try another IDE. JetBrains have many IDE for
various languages

*Hélio Araújo de Oliveira*
Evite correntes de e-mails e combata o spam.
Prefira materiais reciclados, incluindo papel

2016-03-29 16:08 GMT-03:00 ChrisLE <notifications@github.com>:

**Comment by Chris2011** [comment]
This promoting is not helpful for this feature to bring tab suppor for emmet INTO netbeans. There are a lot of others like Sublime, Atom, WebStorm, etc. But if you want to use netbeans than this is your choice. Thats all.

**Comment by junichi11** [comment]
Now, I'm implementing this feature. I have one question.
What would you do when you want to insert "TAB" in other editors?

e.g. 
something[TAB] : when you don't want to expand

**Comment by BugZappr** [comment]
I myself seldom use tabs after text.  It's almost always before the text.  Ideally, there would be some function that could be bound to a key, so, e.g.. <TAB> might be the expand key, <SHIFT-TAB> the expand key, or vice versa.

**Comment by Chris2011** [comment]
I want to use emmet only for HTML, maybe you can build in options to activate/deactivate emmet for each editor. Often it is as @BugZappr said, TAB will used before text, but often I use tab, if I select a piece of code to indent it.

**Comment by junichi11** [comment]
Thanks for the comments!

I'll just add the option for expanding with the TAB key.

Then, I'll implement behaviors as the following:

- If there is text without white space before the caret position, "Tab Space" is added using <kbd>Shift</kbd> + <kbd>TAB</kbd>.
- If text is selected, just indent it. (If you want to expand the selected text, please use another short cut key (e.g. <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>N</kbd>).)
- If an abbreviation can't be expanded, just add "Tab Space".(e.g. `<tag>`<kbd>TAB</kbd>).

Thanks.

**Comment by Chris2011** [comment]
But <kbd>shift</kbd> + <kbd>TAB</kbd> removes the tab which you make with <kbd>TAB</kbd>.

**Comment by junichi11** [comment]
> But shift + TAB removes the tab which you make with TAB.

That's right. But if there are no spaces or tabs, it do nothing. So, I think that there is no problem. (And if there is whitespace before the caret position, the default action of <kbd>shift</kbd> + <kbd>TAB</kbd> is run in my implementation.)

**Comment by junichi11** [comment]
Fixed. 
https://github.com/emmetio/netbeans/releases/tag/v1.1.2

Thanks.

**Comment by kholiavko-roman** [comment]
How I can set up expand abbreviation by tab key in NetBeans IDE 8.2 ?
If I change keymap then default value of TAB key don`t work, and I can insert tab space in my code.

**Comment by Chris2011** [comment]
@kholiavko-roman please use the latest version of the emmet plugin 1.1.2 and then go to options ->miscellaneous -> emmet and check the option "expand abbreviations with the TAB key".

**Comment by kholiavko-roman** [comment]
**Chris2011** , Thank you!
